---
- hosts: localhost
  become: yes
  tasks:
    - name: Clone EVPN Demo
      command: git clone -b evpn https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/evpn
    
    - name: Clone Docker Demo
      command: git clone -b docker-roh https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/docker

    - name: Copy ansible.cfg
      copy: 
        src: ansible.cfg
        dest: /home/cumulus/cldemo-netq/{{item}}/ansible.cfg
      with_items:
        - evpn
        - docker

    - name: Copy Ansible hosts
      copy: 
        src: hosts
        dest: /home/cumulus/cldemo-netq/{{item}}/hosts
      with_items:
        - evpn
        - docker

    - name: Configure Standard OOB Networking
      copy:
        src: interfaces
        dest: /etc/network/interfaces
        backup: yes
      register: apply networking

    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "server: 10.1.3.11"
        line: "server: 192.168.0.254"
      register: restart ts

  handlers:
    - name: apply networking
      command: ifreload -a

    - name: restart ts
      service: 
        name: netq-appliance.service
        state: restarted


- hosts: network
  become: yes
  tasks:
    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "server: 10.1.3.11"
        line: "server: 192.168.0.254"

    - name: Set NetQ config to mgmt vrf
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "vrf: default"
        line: "vrf: mgmt"

    - name: Move NetQ service to Mgmt VRF
      command: "{{item}}"
      with_items:
        - sudo systemctl stop netqd.service
        - sudo systemctl disable netqd.service
        - sudo systemctl enable netqd@mgmt.service
        - sudo systemctl start netqd@mgmt.service
