---
- hosts: localhost
  tasks:
    - name: Clone EVPN Demo
      command: git clone -b evpn https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/evpn
    
    - name: Clone Docker Demo
      command: git clone -b docker-roh https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/docker

    - name: Copy ansible.cfg
      copy: 
        src: ansible.cfg
        dest: /home/cumulus/cldemo-netq/{{item}}/ansible.cfg
      with_items:
        - evpn
        - docker

    - name: Copy Ansible hosts
      copy: 
        src: hosts
        dest: /home/cumulus/cldemo-netq/{{item}}/hosts
      with_items:
        - evpn
        - docker

    - name: Configure Standard OOB Networking
      copy:
        src: interfaces
        dest: /etc/network/interfaces
        backup: yes
      become: yes
      notify: apply networking


    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "  server: 10.1.3.11"
        line: "  server: 192.168.0.254"
        backup: yes
        backrefs: yes
      become: yes
      notify: restart ts

  handlers:
    - name: apply networking
      command: ifreload -a
      become: yes

    - name: restart ts
      service: 
        name: netq-appliance.service
        state: restarted
      become: yes


- hosts: network,servers
  become: yes
  tasks:
    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "  server: 10.1.3.11"
        line: "  server: 192.168.0.254"
        backup: yes
        backrefs: yes

- hosts: network
  become: yes
  tasks:
    - name: Move NetQ service to Mgmt VRF
      command: "{{item}}"
      with_items:
        - systemctl stop netqd.service
        - systemctl stop netq-agent.service
        - systemctl disable netqd.service
        - systemctl disable netq-agent.service
        - systemctl enable netqd@mgmt.service
        - systemctl enable netq-agent@mgmt.service
        - systemctl start netqd@mgmt.service
        - systemctl start netq-agent@mgmt.service

- hosts: servers
  become: yes
  tasks:
    - name: Restart NetQ
      service: 
        name: netq-agent
        state: restarted
