---
- hosts: localhost
  pre_tasks:
    # To prevent unexpected problems, define the minimum Cumulus Linux
    # Release supported by this demo.
    - name: Verify Minimum Software Version
      assert:
        that: "{{ansible_lsb.release | version_compare('3.4', '>=') }}"
        msg: "You appear to be running an older workbench. Please delete your current workbench by adding '/delete' to your workbench URL and request a new one."

  tasks:
    - name: Check if the EVPN demo is already cloned
      stat: 
        path: /home/cumulus/cldemo-netq/evpn
        get_attributes: no
        get_checksum: no
        get_md5: no
      register: evpn

    - name: Check if Docker demo is already cloned
      stat: 
        path: /home/cumulus/cldemo-netq/docker
        get_attributes: no
        get_checksum: no
        get_md5: no
      register: docker

    - name: Clone EVPN Demo
      command: git clone -b evpn https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/evpn
      when: evpn.stat.isdir is not defined

    - name: Clone Docker Demo
      command: git clone -b docker-roh https://github.com/CumulusNetworks/cldemo-netq /home/cumulus/cldemo-netq/docker
      when: docker.stat.isdir is not defined

    - name: Create Ansible Directory
      file:
        path: /etc/ansible
        state: directory
      become: yes

    - name: Copy ansible.cfg
      copy: 
        src: files/ansible.cfg
        dest: /etc/ansible/ansible.cfg
      become: yes

    - name: Copy Ansible hosts
      copy: 
        src: hosts
        dest: /etc/ansible/hosts
      become: yes

    - name: Configure Standard OOB Networking
      copy:
        src: interfaces
        dest: /etc/network/interfaces
        backup: yes
      become: yes
      notify: apply networking


    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "^  server: 10.1.3.11"
        line: "  server: 192.168.0.254"
        backup: yes
        backrefs: yes
      become: yes
      notify: restart ts

  handlers:
    - name: apply networking
      command: ifreload -a
      become: yes

    - name: restart ts
      service: 
        name: netq-appliance.service
        state: restarted
      become: yes


- hosts: network,servers
  become: yes
  tasks:
    - name: Change NetQ IP
      lineinfile:
        path: /etc/netq/netq.yml
        regexp: "^  server: 10.1.3.11"
        line: "  server: 192.168.0.254"
        backup: yes
        backrefs: yes

- hosts: network
  become: yes
  tasks:
    - name: Move NetQ service to Mgmt VRF
      command: "{{item}}"
      with_items:
        - systemctl stop netqd.service
        - systemctl stop netq-agent.service
        - systemctl disable netqd.service
        - systemctl disable netq-agent.service
        - systemctl enable netqd@mgmt.service
        - systemctl enable netq-agent@mgmt.service
        - systemctl start netqd@mgmt.service
        - systemctl start netq-agent@mgmt.service

- hosts: servers,localhost
  become: yes
  tasks:
    - name: Install NTP
      apt:
        name: ntp

    - name: Disable FRR
      copy:
        src: daemons
        dest: /etc/frr/daemons
      notify: restart frr

    - name: Restart NetQ
      service: 
        name: netq-agent
        state: restarted

  handlers:
    - name: restart frr
      service: 
        name: frr.service
        state: restarted

- hosts: servers
  become: yes
  tasks:
    - name: Uninstall Mesos demo
      apt:
        name: "{{item}}"
        state: absent
        autoremove: yes
      with_items:
        - mesos
        - zookeeper
        - chronos
        - marathon

    - name: Fix CITC bonds
      blockinfile:
        path: /etc/rc.local
        block: |
          /sbin/ethtool -s eth1 speed 1000 duplex full
          /sbin/ethtool -s eth2 speed 1000 duplex full
          systemctl restart networking
